services:
  nestjs_api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development
      - PORT=3000
    volumes:
      - ./src:/usr/src/app/src

  mysql_db:
    image: mysql
    ports:
      - '3307:3307'
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=ncc_timesheet
      - MYSQL_USER=ncc_timesheet
      - MYSQL_PASSWORD=ncc_timesheet
      - MYSQL_TCP_PORT=3307
